### ISSUE TITLE
为什么设置自定义域名后打开是空白页面？

### ISSUE THREAD

**Issue by QiTianzu** [mumuchenchen/pikpak#10]
配置流程：
我使用的域名是在 freenom 申请的，在 freenom 中设置所使用域名的名称服务器为 Cloudflare 提供的两个名称服务器，在 GitHub Pages 页面 Custom domain 项下输入子域 pikpak.qitianzu.cf 作为自定义域名，勾选 Enforce HTTPS，在 Cloudflare 中添加名称为 pikpak，目标指向 qitianzu.github.io 的 CNAME 类型的 DNS 记录。
发现问题：
待 DNS 检查完成，打开站点链接 https://pikpak.qitianzu.cf ，页面一片空白，什么都不显示。打开浏览器开发者工具，发现有几个像 "GET https://pikpak.qitianzu.cf/pikpak/assets/index.4a703836.css net::ERR_ABORTED 404" 这样的错误，在新标签页打开相应的链接，确实显示 404 File not found，我尝试把链接中 .cf 后面的 /pikpak 去掉，链接就可以打开了。看来自定义域名 pikpak.qitianzu.cf 只是替换了qitianzu.github.io，而并没有成为 qitianzu.github.io/pikpak 的别名，那么问题出在哪里呢，是我域名配置方式有问题，还是需要修改代码呢？我看大佬配置过 058aa7e 但又删除了 053c339，请问你是怎么配置的？
![2021-11-28 12-11-07-44](https://user-images.githubusercontent.com/50047003/143729263-62996d4e-6d4b-48cd-812b-aced94cf2114.jpg)
![2021-11-28 12-07-01-82](https://user-images.githubusercontent.com/50047003/143729207-493f0747-9928-4f63-8b41-f5a5ee0b8f8a.jpg)
![2021-11-28 12-08-05-30](https://user-images.githubusercontent.com/50047003/143729208-0327e497-292c-4595-9089-98f3468620a6.jpg)

**Comment by QiTianzu** [comment]
发现解决办法了，删除 gh-pages 分支根目录中 index.html 文件第 8，9，10 行中的 "/pikpak/"，并将 assets 文件夹中 index.07bdc771.js 文件中的 "tt="/pikpak/"" 改为 "tt="""，这样修改后就可以正常访问自定义的域名了，要是不想用自己的域名了，想换回原来的，就需要把这两个文件恢复原状。我不会写代码，大佬看看能不能改下代码达到不用手动修改文件就能在 github.io 与自定义域名之间无缝切换的目的。

**Comment by mumuchenchen** [comment]
https://github.com/mumuchenchen/pikpak/commit/12da47ca8f3c881ba082c39be82ef98aef96b095

**Comment by yunxianboy** [comment]
绑定域名后白屏，问题已找出，因为js.css获取的资源多了一个pikpak。

<script type="module" crossorigin src="[/pikpak/assets/index.86466095.js](https://pikpak.xxx.xx/`pikpak`/assets/index.86466095.js)"></script>
    <link rel="modulepreload" href="[/pikpak/assets/vendor.64da71ad.js](https://pikpak.xxx.xx/`pikpak`/assets/vendor.64da71ad.js)">
    <link rel="stylesheet" href="[/pikpak/assets/index.4a703836.css](https://pikpak.xxx.xx/`pikpak`/assets/index.4a703836.css)">
