### ISSUE TITLE
新功能建议

### ISSUE THREAD

**Issue by wnbh** [mumuchenchen/pikpak#2]
建议增加一个提取aria2下载链接的功能，就那种能在控制台调用aria2下载的链接，有可能的话，希望后续能做到批量提取。

**Comment by mumuchenchen** [comment]
![image](https://user-images.githubusercontent.com/93091188/139528309-9f8f94cc-7a87-4665-8e0f-732c703c4daa.png)
可以自己实现相关功能了

**Comment by wnbh** [comment]
牛逼 超出了我的预期 还可以自定义
