### ISSUE TITLE
Bug:safari复制功能失败、链接新窗口打开失败、视频复制画质

### ISSUE THREAD

**Issue by ykxVK8yL5L** [mumuchenchen/pikpak#21]
个人主要使用safari遇到各别问题，不才对源码进行了修改，希望采纳。
https://github.com/ykxVK8yL5L/pikpak/blob/main/list.vue
感谢大神付出

**Comment by mumuchenchen** [comment]
提个pr吧~

**Comment by ykxVK8yL5L** [comment]
>

**Comment by mumuchenchen** [comment]
修改了一下  你看一下

**Comment by ykxVK8yL5L** [comment]
> 修改了一下 你看一下

感谢修复  麻烦再加个目录新窗口打开的功能吧 这样可以避免频繁请求分页数据  我的代码里已经加过了 您可以参考下。
